name: Build, Push, and Update Manifest with Kustomize

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # --- アプリケーションリポジトリのチェックアウト ---
    - name: Checkout app repository
      uses: actions/checkout@v4
      with:
        path: app # ★ ワーキングディレクトリを 'app' に設定

    # --- Docker の設定とビルド・プッシュ ---
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build_image # ★ ステップIDを設定
      uses: docker/build-push-action@v6
      with:
        context: ./app # ★ context を 'app' に変更
        file: ./app/Dockerfile # ★ file パスを変更
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:latest

    # --- マニフェストリポジトリのチェックアウト ---
    - name: Checkout manifest repository
      uses: actions/checkout@v4
      with:
        repository: RyoNagashiro9280/k8s-manifest # ★ マニフェストリポジトリを指定
        path: manifests # ★ ワーキングディレクトリを 'manifests' に設定
        token: ${{ secrets.MANIFEST_REPO_PAT }} # ★ マニフェストリポジトリへのプッシュ権限を持つPAT

    # --- Kustomize のインストール ---
    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin/
    - name: List files in manifests directory
      run: |
        echo "--- Start Listing Files ---"
<<<<<<< HEAD
        pwd 
        ls -laR manifests 
=======
        pwd # 現在のディレクトリを表示
        ls -laR manifests # 'manifests' ディレクトリの中身を詳細に表示
>>>>>>> 36c4a761f4035f9109de28848d64697158919896
        echo "--- End Listing Files ---"

    # --- Kustomize でイメージタグを更新 ---
    - name: Update Kubernetes Manifest with Kustomize
      run: |
        cd manifests # 
        kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web=${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:${{ github.sha }}
        echo "Updated kustomization.yaml:"
        cat kustomization.yaml

    # --- 変更をコミット & プッシュ ---
    - name: Commit and push changes
      run: |
        cd manifests 
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add kustomization.yaml
        if ! git diff --staged --quiet; then
          git commit -m "Update image tag to ${{ github.sha }} [CI]"
          git push
        else
          echo "No changes to commit."
        fi

    # --- 成功メッセージの表示 ---
    - name: Success message
      run: echo "Docker image built, pushed, and Kubernetes manifest updated successfully!"
      if: success() # ★ 成功時のみ実行
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:${{ github.sha }}
        MANIFEST_REPO: RyoNagashiro9280/k8s-manifest
    # --- エラーメッセージの表示 ---
    - name: Error message
      run: echo "An error occurred during the workflow execution."
      if: failure() # ★ 失敗時のみ実行
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:${{ github.sha }}
        MANIFEST_REPO: RyoNagashiro9280/k8s-manifest

  
