name: Build and Push Docker Image

on:
  push: # どんな時にこのワークフローを動かすか
    branches: [ main ] # mainブランチにプッシュされた時だけ動かす (masterブランチなら master に)
  # pull_request: # プルリクエストの時にも動かしたかったらコメントアウトを外す
  #   branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest # ワークフローを実行する環境

    steps:
    - name: Checkout repository # まずリポジトリのコードをチェックアウトする
      uses: actions/checkout@v4

    - name: Set up Docker Buildx # Dockerイメージを効率よくビルドするための準備
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub # Docker Hubにログインする
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # さっき設定したSecretを参照
        password: ${{ secrets.DOCKERHUB_TOKEN }}    # さっき設定したSecretを参照

    - name: Build and push Docker image # イメージをビルドしてプッシュする
      uses: docker/build-push-action@v6
      with:
        context: . # Dockerfileがある場所 (リポジトリのルート)
        file: ./Dockerfile # Dockerfileのパス
        push: true # trueにするとDocker Hubにプッシュする
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-learn-web:latest # イメージ名:タグ名
                                                              # 例: ryonagashiro9280/my-k8s-app:latest
                                                              # ${{ github.sha }} をタグに使うとコミット毎にユニークなタグになる
        # tags: |
        #   ${{ secrets.DOCKERHUB_USERNAME }}/my-k8s-app:latest
        #   ${{ secrets.DOCKERHUB_USERNAME }}/my-k8s-app:${{ github.sha }} # コミットSHAをタグにする例
        #   ${{ secrets.DOCKERHUB_USERNAME }}/my-k8s-app:1.0.0 # バージョンを指定する例